//-----------CODIGO HTML PAGINA DE CONFIGURACION---------------//
String pagina = "<!DOCTYPE html>"
"<html>"
"<head>"
    "<title>Practica</title>"
    "<meta charset=\"UTF-8\">"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
  "<style>"
"* {"
  "box-sizing: border-box;"
"}"

"form {"
  "margin-top: 2rem;"
  "max-width: 600px;"
  "margin-left: auto;"
  "margin-right: auto;"
  "padding: 1em;"
"}"
"form input {"
  "margin-bottom: 1rem;"
  "background: #fff;"
  "border: 1px solid #9c9c9c;"
"}"
"form button {"
  "background: lightgrey;"
  "padding: 0.7em;"
  "border: 0;"
"}"
"form button:hover {"
  "background: gold;"
"}"

"label {"
  "text-align: right;"
  "display: block;"
  "padding: 0.5em 1.5em 0.5em 0;"
"}"

"input {"
  "width: 100%;"
  "padding: 0.7em;"
  "margin-bottom: 0.5rem;"
"}"
"input:focus {"
  "outline: 3px solid gold;"
"}"

"@media (min-width: 400px) {"
  "form {"
    "overflow: hidden;"
  "}"

  "label {"
    "float: left;"
    "width: 200px;"
  "}"

  "input {"
    "float: left;"
    "width: calc(100% - 200px);"
  "}"

  "button {"
    "float: right;"
    "width: calc(100% - 200px);"
  "}"
"}"
  "</style>"
  "</head>"
  "<body>"
    "<div id=\"contenedor\">"
       "<form action=\"guardar_conf\" method=\"get\" id= \"form1\">"
            "<label for=\"ssid\">Nombre de la red</label>"
            "<input name=\"ssid\" type=\"text\">"
            "<label for=\"pass\">Contraseña</label>"
            "<input name=\"pass\" type=\"password\">"              
            "<button type=\"submit\" form=\"form1\" value=\"Submit\">GUARDAR</button>"
        "</form> "
    "</div>";
String paginafin = "</body>"
"</html>";

//-------------------PAGINA DE CONFIGURACION--------------------
void paginaconf() {
  server.send(pagina.length(), "text/html", pagina + mensaje + paginafin); 
}
